import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header.js";

export default function Home() {
  return (
    <>
      <Head>
          <Header/>

          <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Originals Leaderboard
          </h1>
        </div>
      </main>
    </>
  );
}
